config/routes.rb
Rails.application.routes.draw do
  get 'admin_rankings/index'
  get 'rankings/index'
  root to: 'home#index'
  get 'home/index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  devise_for :endusers, controllers: {
    registrations: 'endusers/registrations',
    sessions: "endusers/sessions",
    passwords: "endusers/passwords"
  }

  devise_for :admins, controllers: {
    sessions:      'admins/sessions',
    passwords:     'admins/passwords',
    registrations: 'admins/registrations'
  }

  resources :endusers, only: [:edit, :show, :update, :destroy]
  resources :admins, only: [:index, :show, :destroy]

  resources :trips do
      resource :likes, only: [:create, :destroy]
  end

  resources :admin_trips, only: [:index, :show, :destroy]

  resources :rankings, only: [:index]
  resources :admin_rankings, only: [:index]

end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/day.rb
class Day < ApplicationRecord
	belongs_to :trip
	has_many :stays, dependent: :destroy, inverse_of: :day
    accepts_nested_attributes_for :stays, allow_destroy: true
end

app/models/enduser.rb
class Enduser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :trips, dependent: :destroy
  has_many :likes, dependent: :destroy
  acts_as_paranoid

  validates :name, presence: true
  validates :name, length: { in: 2..20 }
  attachment :profile_image

end

app/models/image.rb
class Image < ApplicationRecord
	belongs_to :stay
	attachment :image
end

app/models/like.rb
class Like < ApplicationRecord
	belongs_to :trip
	belongs_to :enduser
end

app/models/stay.rb
class Stay < ApplicationRecord
	belongs_to :day
	has_many :images, dependent: :destroy, inverse_of: :stay
	accepts_nested_attributes_for :images, allow_destroy: true
	accepts_attachments_for :images
  validates :comment,    length: { maximum: 250 }      # 「250文字以下」

    before_save :update_lonlat

    def update_lonlat
        lonlat = place_to_lonlat(read_attribute(:place))
        write_attribute(:lonlat, lonlat)
    end

    # 住所を保存用経緯度に変換
    def place_to_lonlat(place)
      result = Geocoder.search(place)
      if result.first
        lonlat = result.first.coordinates
        return lonlat.join(',')
      else
        return false
      end
    end

end

app/models/trip.rb
class Trip < ApplicationRecord
	belongs_to :enduser
	has_many :days, dependent: :destroy, inverse_of: :trip
	accepts_nested_attributes_for :days, allow_destroy: true
    validates :title,    length: { in: 1..50 }        # 「1文字以上50文字以下」
    validates :subtitle,    length: { maximum: 250 }      # 「250文字以下」
	has_many :likes, dependent: :destroy
	def enduser
      return Enduser.find_by(id: self.enduser_id)
    end

	def liked_by?(enduser)
		likes.where(enduser_id: enduser.id).exists?
    end
end

app/controllers/admins_controller.rb
class AdminsController < ApplicationController

  def index
    @q = Enduser.ransack(params[:q])
    @endusers = @q.result(distinct: true).page(params[:page]).per(10).reverse_order
  end

  def search
    @q = Enduser.search
    @endusers = @q.result(distinct: true)
  end

  def show
      @enduser = Enduser.find(params[:id])
      @trips = @enduser.trips.page(params[:page]).per(10).reverse_order
  end

  def destroy
      Enduser.find(params[:id]).destroy
    if admin_signed_in?
      redirect_to trips_path
    else
      redirect_to admins_trips_path
    end
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
    def create
        @trip = Trip.find(params[:trip_id])
        @like = current_enduser.likes.new(trip_id: @trip.id)
        @like.save
        render :create
    end
    def destroy
        @trip = Trip.find(params[:trip_id])
        @like = current_enduser.likes.find_by(trip_id: @trip.id)
        @like.destroy
        render :destroy
    end
end

app/controllers/trips_controller.rb
class TripsController < ApplicationController
before_action :ensure_correct_enduser, {only: [:edit, :update, :destroy]}
before_action :search

  def ensure_correct_enduser
  @trip = Trip.find_by(id: params[:id])
    if current_enduser.id != @trip.enduser_id
       flash[:notice] = "権限がありません"
       redirect_to trips_path
    end
  end

  def index
  	@q = Trip.ransack(params[:q])
    @trips = @q.result(distinct: true).page(params[:page]).per(10).reverse_order
    @random = Image.all.shuffle
  end

  def search
    @q = Trip.search
    @trips = @q.result(distinct: true)
  end

  def show
    @trip = Trip.find_by(id: params[:id])
    @trips = Trip.all
    @enduser = @trip.enduser
  end

  def new
  	@trip = Trip.new
  	@day = @trip.days.build
  	@stay = @day.stays.build
  	@image = @stay.images.build
  end

  def create
      @trip = Trip.new(trip_params)
      @trip.enduser_id = current_enduser.id
      @enduser = current_enduser
      @trips = Trip.all.order(created_at: :desc)
      if @trip.save
         redirect_to trips_path
         flash[:notice] = "You have creatad book successfully."
      else
         render 'trips/new'
      end
  end

  def edit
      @trip = Trip.find(params[:id])
      if @trip.enduser == current_enduser
      else
        redirect_to trips_path
      end
  end

  def update
      @trip = Trip.find(params[:id])
      @trip.update(trip_params)
      if @trip.save
        redirect_to trip_path(@trip)
        flash[:notice] = "You have edited book successfully"
      else
        render :edit
      end
  end

  def destroy
      @trip = Trip.find(params[:id])
      @trip.destroy
      redirect_to trips_path
  end

  private
    def trip_params
    params.require(:trip).permit(:title, :subtitle,
    	  days_attributes: [:id, :day, :_destroy,
        stays_attributes: [:id, :time, :country, :place, :money, :comment, :status, :lonlat, :_destroy,
        images_attributes: [:id, :image, :_destroy]]])
    end
end

app/helpers/admin_trips_helper.rb
module AdminTripsHelper
end

app/helpers/admins_helper.rb
module AdminsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/endusers_helper.rb
module EndusersHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/rankings_helper.rb
module RankingsHelper
end

app/helpers/trips_helper.rb
module TripsHelper
end

app/views/admins/index.html.erb
<div class="container">
	<h1>ユーザー一覧</h1>

<!-- 検索フォーム -->
<div class="arrivalbtn">
  <%= search_form_for(@q, url:admins_path) do |f| %>
    <%= f.label :'ユーザー検索' %>
    <%= f.search_field :name_cont %>
    <%= f.submit '検索', class: 'btn btn-primary'  %>
  <% end %>
</div>

		<div class="row">
			<table class="table table-respansive">
			  <table class="table table-hover">
				<% @endusers.each do |enduser| %>
			      <tr>
			      	<td><%= attachment_image_tag enduser, :profile_image, :fill, 50, 50, class: "img-circle profile-thumb", fallback: "/images/no_image.jpg"%></td>
			        <td><%= link_to enduser.name, admin_path(enduser.id) %></br></td>
			        <td><%= enduser.email %></br></td>
			      </tr>
			    <% end %>
			  </table>
			</table>
		</div>
</div>

app/views/admins/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admins/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end %>
<% end %>

app/views/admins/show.html.erb
<div class="container">
  <div class="row">
  	<h1><%= @enduser.name %>の詳細ページ</h1>
    <div style="padding: 5px; margin-top: 20px; margin-bottom: 10px; border: 1px solid #00008B; border-radius: 10px;">
      <table class="table table-striped">
        <tbody>
        	<%= attachment_image_tag @enduser, :profile_image, :fill, 128, 128, class: "img-circle profile-thumb", fallback: "/images/no_image100.jpg"%>
          <tr style="background-color:#f5f5f5">
	          <th><p>お名前</p></th>
	          <th><p>メールアドレス</p></th>
	      </tr>
	      <tr style="background-color:#f5f5f5">
	          <th><%= @enduser.name %></th>
      	      <th><%= @enduser.email %></th>
          </tr>
        </tbody>
      </table>
      <% if admin_signed_in? %>
       <div class="field">
        <%= link_to "強制退会", admin_path, method: :delete, data: { confirm: 'Are you sure?' }, class: "pull-denger", class: "btn btn-danger btn-xs" %>
       </div>
      <% end %>
    </div>

    <div class="row">
      <div class="trip">
        <table class="table table-respansive">
          <table class="table table-hover">
            <% @trips.each do |trip| %>
              <tr>
                <td><%= link_to trip.title, trip_path(trip.id) %></td>
                <td><%= trip.subtitle %></td>
                <td><span class="glyphicon glyphicon-heart" aria-hidden="true"> <%= trip.likes.count %></td>
                <td><%= attachment_image_tag trip.enduser, :profile_image, :fill, 50, 50, class: "img-circle profile-thumb", fallback: "/images/no_image.jpg"%></td>
                <td><%= trip.enduser.name %></td>
      </div>
              </tr>
          <% end %>
          </table>
        </table>
    </div>
      <div class="paginate" style="font-size: 20px">
        <%= paginate(@trips) %>
      </div>

  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<div class="main-container">
  <head>
    <title>Tabirepi</title>
      <!-- API 地図データ読み込み -->
      <meta charset="utf-8" />
      <link rel="stylesheet" href="https://unpkg.com/leaflet@1.0.3/dist/leaflet.css" />
      <link rel="stylesheet" href="https://rawgit.com/k4r573n/leaflet-control-osm-geocoder/master/Control.OSMGeocoder.css" />
      <script src="https://unpkg.com/leaflet@1.0.3/dist/leaflet.js"></script>
      <script src="https://rawgit.com/k4r573n/leaflet-control-osm-geocoder/master/Control.OSMGeocoder.js"></script>
      <%= csrf_meta_tags %>
      <%= csp_meta_tag %>

      <!-- jQuery slick -->
      <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
      <link rel="stylesheet" type="text/css" href="//cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.css"/>
      <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
      <script type="text/javascript" src="//cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.min.js"></script>

      <!-- application cssファイル読み込み -->
      <link rel="stylesheet" href="application.scss" type="text/css">

      <!-- ハンバーガーメニュー -->
      <meta http-equiv="X-UA-Compatible" content="IE=edge">
      <meta name="viewport" content="width=device-width">
      <link rel="stylesheet" href="css/style.css" media="all">

  </head>

    <header>
      <nav class="navbar navbar-inverse" style="background-color: #89c7de;">
        <div class="container">
          <div class="row">

              <div class="col-md-4">
                <% if admin_signed_in? %>
                  <%= link_to admin_trips_path do %>
                    <h4><div class="sub logocolor">あなたの旅をレシピする</div></h4></br>
                    <h2><div class="title logocolor">Tabirepi</div></h2>
                  <% end %>
                <% else %>
                  <%= link_to trips_path do %>
                    <h4><div class="sub logocolor">あなたの旅をレシピする</div></h4></br>
                    <h2><div class="title logocolor">Tabirepi</div></h2>
                  <% end %>
                <% end %>
              </div>
          </div>
        </div>
      </nav>

      <!-- ハンバーガーメニュー　ここから -->
      <div id="sp-menu">
        <h1>MENU</h1></br>
        <% if enduser_signed_in? %>
          <ul class="list-inline">
            <li><%= link_to sanitize('<i class="glyphicon glyphicon-pencil"></i> ') + '新規旅行情報追加', new_trip_path %></li></br>
            <li><%= link_to sanitize('<i class="glyphicon glyphicon-home"></i> ') + '一覧画面', trips_path %>
            </li></br>
            <li><%= link_to sanitize('<i class="glyphicon glyphicon-tower"></i> ') + 'ランキング', rankings_path %>
            </li></br>
            <li><%= link_to sanitize('<i class="glyphicon glyphicon-user"></i> ') + 'マイページ', enduser_path(current_enduser.id) %>
            </li></br>
            <li><%= link_to sanitize('<i class="glyphicon glyphicon-log-out"></i> ') + 'ログアウト', destroy_enduser_session_path, method: :delete %>
            </li></br>
            <li><%= link_to sanitize('<i class="glyphicon glyphicon-trash"></i> ') + "退会", enduser_registration_path, method: :delete, data: { confirm: 'Are you sure?' }, class: "pull-danger", class: "btn btn-xs" %>
            </li></br>
          </ul>
        <% elsif admin_signed_in? %>
            <ul class="list-inline">
              <li><%= link_to sanitize('<i class="glyphicon glyphicon-user"></i> ') + 'ユーザー一覧', admins_path %></li></br>
              <li><%= link_to sanitize('<i class="glyphicon glyphicon-home"></i> ') + '旅行情報一覧', admin_trips_path %></li></br>
              <li><%= link_to sanitize('<i class="glyphicon glyphicon-tower"></i> ') + 'ランキング', admin_rankings_path %>
              </li></br>
              <li><%= link_to sanitize('<i class="glyphicon glyphicon-log-out"></i> ') + 'ログアウト', destroy_admin_session_path, method: :delete %>
              </li></br>
            </ul>
        <% else %>
            <ul class="list-inline">
              <li><%= link_to sanitize('<i class="glyphicon glyphicon-home"></i> ') + 'ホーム', trips_path %>
              </li></br>
              <li><%= link_to sanitize('<i class="glyphicon glyphicon-tower"></i> ') + 'ランキング', rankings_path %>
              </li></br>
              <li><%= link_to sanitize('<i class="glyphicon glyphicon-edit"></i> ') + '会員登録', new_enduser_registration_path %>
              </li></br>
              <li><%= link_to sanitize('<i class="glyphicon glyphicon-log-in"></i> ') + 'ログイン', enduser_session_path %>
              </li></br>
            </ul>
        <% end %>
      </div>

      <div id="hm-icon">
        <a class="menu-trigger" href="#">
          <span></span>
          <span></span>
          <span></span>
        </a>
      </div>

      <script type="text/javascript" src="js/jquery.min.js"></script>
      <script type="text/javascript" src="js/script.js"></script>

      <script>
        $(document).ready(function() {
        $('.menu-trigger').on('click', function() {
          $(this).toggleClass('active');
          $('#sp-menu').fadeToggle();
          return false;
        });
       });
      </script>
      <!-- ハンバーガーメニュー　ここまで -->

    </header>

    <main>
      <%= yield %>
    </main>

    <footer>
      <p>Tabirepi.inc</p>
    </footer>
</div>
</html>