config/routes.rb
Rails.application.routes.draw do
  get 'admin_rankings/index'
  get 'rankings/index'
  root to: 'home#index'
  get 'home/index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  devise_for :endusers, controllers: {
    registrations: 'endusers/registrations',
    sessions: "endusers/sessions",
    passwords: "endusers/passwords"
  }

  devise_for :admins, controllers: {
    sessions:      'admins/sessions',
    passwords:     'admins/passwords',
    registrations: 'admins/registrations'
  }

  resources :endusers, only: [:edit, :show, :update, :destroy]
  resources :admins, only: [:index, :show, :destroy]

  resources :trips do
      resource :likes, only: [:create, :destroy]
  end

  resources :admin_trips, only: [:index, :show, :destroy]

  resources :rankings, only: [:index]
  resources :admin_rankings, only: [:index]

end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/day.rb
class Day < ApplicationRecord
	belongs_to :trip
	has_many :stays, dependent: :destroy, inverse_of: :day
    accepts_nested_attributes_for :stays, allow_destroy: true
end

app/models/enduser.rb
class Enduser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :trips, dependent: :destroy
  has_many :likes, dependent: :destroy
  acts_as_paranoid

  validates :name, presence: true
  validates :name, length: { in: 2..20 }
  attachment :profile_image

end

app/models/image.rb
class Image < ApplicationRecord
	belongs_to :stay
	attachment :image
end

app/models/like.rb
class Like < ApplicationRecord
	belongs_to :trip
	belongs_to :enduser
end

app/models/stay.rb
class Stay < ApplicationRecord
	belongs_to :day
	has_many :images, dependent: :destroy, inverse_of: :stay
	accepts_nested_attributes_for :images, allow_destroy: true
	accepts_attachments_for :images
  validates :comment,    length: { maximum: 250 }      # 「250文字以下」

    before_save :update_lonlat

    def update_lonlat
        lonlat = place_to_lonlat(read_attribute(:place))
        write_attribute(:lonlat, lonlat)
    end

    # 住所を保存用経緯度に変換
    def place_to_lonlat(place)
      result = Geocoder.search(place)
      if result.first
        lonlat = result.first.coordinates
        return lonlat.join(',')
      else
        return false
      end
    end

end

app/models/trip.rb
class Trip < ApplicationRecord
	belongs_to :enduser
	has_many :days, dependent: :destroy, inverse_of: :trip
	accepts_nested_attributes_for :days, allow_destroy: true
    validates :title,    length: { in: 1..50 }        # 「1文字以上50文字以下」
    validates :subtitle,    length: { maximum: 250 }      # 「250文字以下」
	has_many :likes, dependent: :destroy
	def enduser
      return Enduser.find_by(id: self.enduser_id)
    end

	def liked_by?(enduser)
		likes.where(enduser_id: enduser.id).exists?
    end
end

app/controllers/admins_controller.rb
class AdminsController < ApplicationController

  def index
    @q = Enduser.ransack(params[:q])
    @endusers = @q.result(distinct: true).page(params[:page]).per(10).reverse_order
  end

  def search
    @q = Enduser.search
    @endusers = @q.result(distinct: true)
  end

  def show
      @enduser = Enduser.find(params[:id])
      @trips = @enduser.trips.page(params[:page]).per(10).reverse_order
  end

  def destroy
      Enduser.find(params[:id]).destroy
    if admin_signed_in?
      redirect_to trips_path
    else
      redirect_to admins_trips_path
    end
  end

end

app/controllers/endusers_controller.rb
class EndusersController < ApplicationController

  def show
  	  @enduser = Enduser.find(params[:id])
      @trips = @enduser.trips.page(params[:page]).per(10).reverse_order
  end

  def edit
  	  @enduser = Enduser.find(params[:id])
      if @enduser == current_enduser
      else
        redirect_to enduser_path(current_enduser)
      end
  end

  def update
      @enduser = Enduser.find(params[:id])
      if @enduser.update(enduser_params)
         redirect_to enduser_path(@enduser.id)
      else
        flash.now[:alert] = "正しく記入してください。"
      	render :edit
      end
  end

  private
  def enduser_params
      params.require(:enduser).permit(:name, :email, :profile_image)
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
    def create
        @trip = Trip.find(params[:trip_id])
        @like = current_enduser.likes.new(trip_id: @trip.id)
        @like.save
        render :create
    end
    def destroy
        @trip = Trip.find(params[:trip_id])
        @like = current_enduser.likes.find_by(trip_id: @trip.id)
        @like.destroy
        render :destroy
    end
end

app/controllers/rankings_controller.rb
class RankingsController < ApplicationController

	  def index
          @trips = Trip.find(Like.group(:trip_id).order('count(trip_id) desc').limit(30).pluck(:trip_id))
	  end

end

app/controllers/trips_controller.rb
class TripsController < ApplicationController
before_action :ensure_correct_enduser, {only: [:edit, :update, :destroy]}
before_action :search

  def ensure_correct_enduser
  @trip = Trip.find_by(id: params[:id])
    if current_enduser.id != @trip.enduser_id
       flash[:notice] = "権限がありません"
       redirect_to trips_path
    end
  end

  def index
  	@q = Trip.ransack(params[:q])
    @trips = @q.result(distinct: true).page(params[:page]).per(10).reverse_order
    @random = Image.all.shuffle
  end

  def search
    @q = Trip.search
    @trips = @q.result(distinct: true)
  end

  def show
    @trip = Trip.find_by(id: params[:id])
    @trips = Trip.all
    @enduser = @trip.enduser
  end

  def new
  	@trip = Trip.new
  	@day = @trip.days.build
  	@stay = @day.stays.build
  	@image = @stay.images.build
  end

  def create
      @trip = Trip.new(trip_params)
      @trip.enduser_id = current_enduser.id
      @enduser = current_enduser
      @trips = Trip.all.order(created_at: :desc)
      if @trip.save
         redirect_to trips_path
         flash[:notice] = "You have creatad book successfully."
      else
         render 'trips/new'
      end
  end

  def edit
      @trip = Trip.find(params[:id])
      if @trip.enduser == current_enduser
      else
        redirect_to trips_path
      end
  end

  def update
      @trip = Trip.find(params[:id])
      @trip.update(trip_params)
      if @trip.save
        redirect_to trip_path(@trip)
        flash[:notice] = "You have edited book successfully"
      else
        render :edit
      end
  end

  def destroy
      @trip = Trip.find(params[:id])
      @trip.destroy
      redirect_to trips_path
  end

  private
    def trip_params
    params.require(:trip).permit(:title, :subtitle,
    	  days_attributes: [:id, :day, :_destroy,
        stays_attributes: [:id, :time, :country, :place, :money, :comment, :status, :lonlat, :_destroy,
        images_attributes: [:id, :image, :_destroy]]])
    end
end

app/helpers/admin_rankings_helper.rb
module AdminRankingsHelper
end

app/helpers/admin_trips_helper.rb
module AdminTripsHelper
end

app/helpers/admins_helper.rb
module AdminsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/endusers_helper.rb
module EndusersHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/rankings_helper.rb
module RankingsHelper
end

app/helpers/trips_helper.rb
module TripsHelper
end

app/views/likes/_like.html.erb
<!-- いいね機能 -->
<div class="like">
  <% if enduser_signed_in? %>
    <% if trip.liked_by?(current_enduser) %>
        <%= button_to trip_likes_path(trip), method: :delete, remote: true do %>
          <i class="fa fa-heart" aria-hidden="true" style="color: red;">
          <span class="glyphicon glyphicon-heart" aria-hidden="true"> <%= trip.likes.count %></span></i>
        <% end %>
    <% else %>
        <%= button_to trip_likes_path(trip), method: :post, remote: true do %>
          <i class="fa fa-heart-o" aria-hidden="true">
          <span class="glyphicon glyphicon-heart-empty" aria-hidden="true"> <%= trip.likes.count %></span></i>
        <% end %>
    <% end %>
  <% else %>
    <span class="glyphicon glyphicon-heart" aria-hidden="true"> <%= trip.likes.count %></span>
  <% end %>
</div>

app/views/likes/create.js.erb
$("#favo").html("<%= j(render 'like', { trip: @trip }) %>")

app/views/likes/destroy.js.erb
$("#favo").html("<%= j(render 'like', { trip: @trip }) %>")

app/views/trips/_day_fields.html.erb
<div class="nested-fields">
	<!-- 何日目かをプルダウンで選択 -->
  <div class="newday">
  	<%= f.number_field :day, min: 1 %>日目</br></br>
    <button type="button" class="btn btn-outline-warning btn-sm">
      <%= link_to_remove_association "remove day", f, class: "btn btn-warning btn-xs" %>
    </button></br></br>
  </div>
    <div id="parents">
      <%= f.fields_for :stays do |stay| %>
        <%= render 'stay_fields', f: stay %>
      <% end %>
    </div>
    <div id="links">
        <%= link_to_add_association 'add stays', f, :stays, class: "btn btn-primary btn-xs" %></br></br>
    </div>
</div>

app/views/trips/_image_fields.html.erb
<div class="nested-fields">
  <%= f.attachment_field :image %></br>
    <div id="links">
      <button type="button" class="btn btn-outline-warning btn-sm">
        <%= link_to_remove_association "remove image", f, class: "btn btn-warning btn-xs" %>
      </button></br></br>
	</div>
</div>

app/views/trips/_map.html.erb
<!-- APIでマップ実装 -->

    <script type="text/javascript">
        var osmUrl='http://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png';
        var osmAttrib='&copy; <a href="http://osm.org/copyright">OpenStreetMap</a> contributors'
        var osm = new L.TileLayer(osmUrl, {attribution: osmAttrib});
        var map = new L.Map('map').addLayer(osm).setView([48.84845, 10.29694], 1);

        // Control OSM Geocoder
        var option = {
          position: 'topright', // topright, topleft, bottomright, bottomleft
          text: '検索',
          placeholder: '検索条件を入力してください。'
        }
        var osmGeocoder = new L.Control.OSMGeocoder(option);
        map.addControl(osmGeocoder);

        // Script for adding marker on map click
        function onMapClick(e) {

            var marker = L.marker(e.latlng, {
                draggable: true,
                title: "Resource location",
                alt: "Resource Location",
                riseOnHover: true
            }).addTo(map)
                .bindPopup(e.latlng.toString()).openPopup();

            // Update marker on changing it's position
            marker.on("click", function (ev) {

                var chagedPos = ev.target.getLatLng();
                this.bindPopup(chagedPos.toString()).openPopup();

            });

            marker.on("dragend", function (hv){
                map.removeLayer(hv.target);
            });
        }


        map.on('click', onMapClick);
        marker.on('click', onMarkerClick);
    </script>

app/views/trips/_mapreader.html.erb
    <!-- APIでマップ実装 -->
    <% i = 0 %>
      <% @trip.days.each do |day| %>
        <% day.stays.each do |stay| %>
        <% i += 1 %>
        <div id="<%= i %>" data-json="<%= stay.lonlat.to_json %>" ></div>
        <% end %>
      <% end %>
        <div id="j_end" data-json="<%= i.to_json %>" ></div>
    <script type="text/javascript">
            var osmUrl='http://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png';
            var osmAttrib='&copy; <a href="http://osm.org/copyright">OpenStreetMap</a> contributors'
            var osm = new L.TileLayer(osmUrl, {attribution: osmAttrib});
            var map = new L.Map('map').addLayer(osm).setView([48.84845, 10.29694], 1);
            var j_end = JSON.parse(document.getElementById("j_end").dataset.json);
            for (var j=1; j<=j_end; j++){
                var lonlat = JSON.parse(document.getElementById(j).dataset.json);
                if (lonlat != null){
                    L.marker( lonlat.split(',')).addTo(map);
                }
            }
    </script>

app/views/trips/_stay_fields.html.erb
<div class="nested-fields">
    <!-- 時間を選択 -->
	<%= f.time_select :time %></br></br>
	<!-- 国名をプルダウンで選択 -->
	<%= f.country_select :country %></br></br>
	<!-- 具体的な場所を記述 -->
	<%= f.text_field :place, :placeholder => "訪れた場所", :size=>"20" %></br></br>
	<!-- 状況　出発or到着or滞在 -->
	<%= f.select :status, [['出発', '出発'], ['到着', '到着'], ['滞在', '滞在']] %></br></br>
	<!-- 費用 -->
	<%= f.number_field :money,min: 0 %>¥</br></br>
    <!-- 写真 -->
	<%= f.fields_for :images do |image| %>
	  <%= render 'image_fields', f: image %>
	<% end %>
    <!-- コメント -->
	<%= f.text_area :comment, :placeholder => "コメント記入欄(250文字以下)", :size=>"30x10" %></br></br>
	<div id="links">
      <%= link_to_add_association 'add image', f, :images, class: "btn btn-primary btn-xs"%></br></br>
    </div>
	<div id="links">
	  <button type="button" class="btn btn-outline-warning btn-sm">
        <%= link_to_remove_association "remove stay", f, class: "btn btn-warning btn-xs" %>
      </button></br></br>
	</div>
</div>

app/views/trips/_tripform.html.erb
  <%= form_with model: @trip ,local: true do |f| %>
    <!-- タイトル -->
  	<%= f.text_field :title, :placeholder => "旅のタイトルを記入して下さい(1文字以上50文字以下)", :size=>"50" %></br></br>
  	<!-- 概要 -->
  	<%= f.text_area :subtitle, :placeholder => "旅の概要を記入して下さい(250文字以下)", :size=>"40x2" %></br></br>

    <div id="parents">
    	  <%= f.fields_for :days do |day| %>
    	    <%= render 'day_fields', f: day %>
    	  <% end %>
    </div>

    <div class="links">
      <%= link_to_add_association 'add days', f, :days, class: "btn btn-primary btn-xs"%>
    </div></br>

    <div class="actions" style="margin-bottom: 40px;">
      <%= f.submit '記録する' %>
    </div>
  <% end %>

app/views/trips/edit.html.erb
<div class="container">
  <h2>旅行情報を編集する</h2></br>
    <div class="new">
      <div class="row">
        <div class="col-md-5">
          <%= form_with(model: @trip, local: true, url: trip_path, method: :patch) do |s| %>
            <div class="field">
              <%= s.text_field :title, :placeholder => "旅のタイトルを記入ください(1文字以上50文字以下)", :size=>"30" %></br></br>
              <%= s.text_area :subtitle, :placeholder => "旅の概要を記入してください(250文字以下)", :size=>"30x2" %></br>
              <div id="parents">
                <%= s.fields_for :days do |day| %>
                  <%= render 'day_fields', f: day %>
                <% end %>
              </div>
              <div class="links">
                  <%= link_to_add_association 'add days', s, :days, class: "btn btn-primary btn-xs"%>
              </div></br></br>
              <div class="actions" style="margin-bottom: 40px;">
                <%= s.submit "旅行情報更新" %>
              </div>
            </div>
          <% end %>
        </div>
      </div>
    </div>

  <!-- APIでマップ機能実装 -->
  <div class="col-md-7">
    <div class="row">
      <div class="mapnew">
        <div class="maptext">
          <p>● 地図上でクリックすると緯度,経度が表示されます。</p>
          <p>● 地図上のマーカーを動かすことでマーカーを削除できます。</p>
          <p>● 地図上に訪れた場所がない場合は、緯度,経度で記入するとマーカーが表示されます。</p>
        </div>
      </div>
    </div>

    <div class="row">
      <div id="map">
        <div class="mapcss">
          <%= render :partial => "map" %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/trips/index.html.erb
<div class="container">

  <div class="col-md-12">
    <%= render :partial => "image" %>
  </div></br>

  <!-- 検索フォーム -->
  <div class="col-md-12">
    <div class="searchbtn">
      <%= search_form_for(@q, url:trips_path) do |f| %>
        <span class="glyphicon glyphicon-search" aria-hidden="true"></span>
        <%= f.search_field :title_or_subtitle_cont %>
        <%= f.submit '検索', class: 'btn btn-primary'  %>
      <% end %>
    </div>
  </div>

  <body>
    <div class="row">
      <div class="trip">
        <table class="table table-respansive">
          <table class="table table-hover">
            <% @trips.each do |trip| %>
                  <tr>
                    <td><%= link_to trip.title, trip_path(trip.id) %></td>
                    <td><%= trip.subtitle %></td>
                    <td><span class="glyphicon glyphicon-heart" aria-hidden="true"> <%= trip.likes.count %></span></td>
                    <td><%= attachment_image_tag trip.enduser, :profile_image, :fill, 50, 50, class: "img-circle profile-thumb", fallback: "/images/no_image.jpg"%></td>
                    <td><%= trip.enduser.name %></td>
      </div>
                  </tr>
          <% end %>
          </table>
        </table>
    </div>
      <div class="paginate" style="font-size: 20px">
  	    <%= paginate(@trips) %>
  	  </div>

      <% if enduser_signed_in? %>
  	  <ul class="list-inline">
  	    <li><%= link_to "新規旅行情報追加",  new_trip_path, class: "btn btn-primary btn-lg" %></li>
  	  </ul>
  	<% else %>
  	  <ul class="list-inline">
  	    <li><%= link_to "新規旅行情報追加",  enduser_session_path, class: "btn btn-primary btn-lg" %></li>
  	  </ul>
  	<% end %></br></br>
  </body>
</div>

app/views/trips/new.html.erb
<div class="container">
	<h2>新しく投稿する</h2></br>
  <div class="new">
	<div class="row">
	  <div class="col-md-5">
	    <%= render 'tripform', trip: @trip %>
      </div>
	</div>
  </div>
	<!-- APIでマップ機能実装 -->
	<div class="col-md-7">
		<div class="row">
			<div class="mapnew">
			  <div class="maptext">
			      <p>● 地図上でクリックすると緯度,経度が表示されます。</p>
			      <p>● 地図上のマーカーを動かすことでマーカーを削除できます。</p>
			      <p>● 地図上に訪れた場所がない場合は、緯度,経度で記入するとマーカーが表示されます。</p>
			  </div>
		    </div>
		</div>

		<div class="row">
			<div id="map">
			  <div class="mapcss">
				<%= render :partial => "map" %>
		      </div>
		    </div>
	    </div>
	</div>
</div>

app/views/trips/show.html.erb
<div class="container">
  <div class="new">
    <div class="row">
      <div class="col-md-5">
            <div class="margin-bottom">
              <b style="font-size:14px;"><%= @trip.title %></br></b>
              <b style="font-size:10px;"><%= @trip.subtitle %><br></b>
            </div>

            <!-- いいね機能 -->
            <div id="favo">
               <%= render 'likes/like', trip: @trip %>
            </div>

            <div class="tripdata">
              <% @trip.days.each do |day| %>
                <% day.stays.each do |stay| %>
                    <b style="font-size:20px;"><%= day.day %>日目</br></b>
                    <%= stay.time.strftime("%R") %>
                    <%= stay.status %>
                    <%= stay.country %></br>
                    <%= stay.place %>
                    <%= stay.money %>¥</br>
                    <%= stay.comment %></br>
                    <table class="table">
                      <% stay.images.each do |image| %>
                        <tr>
                          <td><%= attachment_image_tag image, :image, :fill, 100, 100%></td>
                        </tr>
                      <% end %>
                    </table>
                <% end %>
              <% end %>
            </div>

          <div class="tripshowbtn">
            <% if enduser_signed_in? %>
              <% if current_enduser.id == @enduser.id %>
                <td><%= link_to "編集", edit_trip_path(@trip), class: "btn btn-success btn-xs" %></td>
                <td><%= link_to "削除", trip_path, model: @trip, method: :delete, data: { confirm: 'Are you sure?' }, class: "pull-danger", class: "btn btn-danger btn-xs" %></td></br></br>
              <% end %>
            <% else %>
            <% end %>
          <%= link_to "一覧画面に行く", trips_path, class: 'btn btn-default' %>
          </div>
      </div>
    </div>
  </div>

  <div class="col-md-7">
    <div class="row">
      <div id="map">
        <div class="mapcss">
          <%= render :partial => "mapreader" %>
        </div>
      </div>
    </div>
  </div>
</div>