config/routes.rb
Rails.application.routes.draw do
  get 'admin_rankings/index'
  get 'rankings/index'
  root to: 'home#index'
  get 'home/index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  devise_for :endusers, controllers: {
    registrations: 'endusers/registrations',
    sessions: "endusers/sessions",
    passwords: "endusers/passwords"
  }

  devise_for :admins, controllers: {
    sessions:      'admins/sessions',
    passwords:     'admins/passwords',
    registrations: 'admins/registrations'
  }

  resources :endusers, only: [:edit, :show, :update, :destroy]
  resources :admins, only: [:index, :show, :destroy]

  resources :trips do
      resource :likes, only: [:create, :destroy]
  end

  resources :admin_trips, only: [:index, :show, :destroy]

  resources :rankings, only: [:index]
  resources :admin_rankings, only: [:index]

end

app/models/enduser.rb
class Enduser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :trips, dependent: :destroy
  has_many :likes, dependent: :destroy
  acts_as_paranoid

  validates :name, presence: true
  validates :name, length: { in: 2..20 }
  attachment :profile_image

end

app/controllers/endusers/confirmations_controller.rb
# frozen_string_literal: true

class Endusers::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/endusers/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Endusers::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/endusers/passwords_controller.rb
# frozen_string_literal: true

class Endusers::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/endusers/registrations_controller.rb
# frozen_string_literal: true

class Endusers::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/endusers/sessions_controller.rb
# frozen_string_literal: true

class Endusers::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/endusers/unlocks_controller.rb
# frozen_string_literal: true

class Endusers::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/endusers_controller.rb
class EndusersController < ApplicationController

  def show
  	  @enduser = Enduser.find(params[:id])
      @trips = @enduser.trips.page(params[:page]).per(10).reverse_order
  end

  def edit
  	  @enduser = Enduser.find(params[:id])
      if @enduser == current_enduser
      else
        redirect_to enduser_path(current_enduser)
      end
  end

  def update
      @enduser = Enduser.find(params[:id])
      if @enduser.update(enduser_params)
         redirect_to enduser_path(@enduser.id)
      else
        flash.now[:alert] = "正しく記入してください。"
      	render :edit
      end
  end

  private
  def enduser_params
      params.require(:enduser).permit(:name, :email, :profile_image)
  end

end

app/helpers/endusers_helper.rb
module EndusersHelper
end

app/views/endusers/edit.html.erb
  <div class="container">
   <div class="row sketchborder">
    <div class="col-md-8 col-md-offset-2">
     <h1 class="center-cd">ユーザー編集画面</h1>
      <%= form_for(@enduser) do |f| %>
       <div class="form-group has-icon">
        <!-- プロフィール画像 -->
        <div class="form-group has-icon">
          <div class="enduser-edit-image">
            <%= attachment_image_tag @enduser, :profile_image, :fill, 60, 60, class: "img-circle pull-left profile-thumb", fallback: "/images/no_image.jpg"%>
          </div>
            <label class="control-label sr-only" for="inputEmail">ProfileImage</label>
            <%= f.attachment_field :profile_image, placeholder: "プロフィール画像", class: "enduser-edit-form" %>
        </div></br></br>
        <!-- 名前 -->
        <div class="field">
          <%= f.label :お名前, class: 'labelname' %><br/>
          <%= f.text_field :name, autofocus: true, class: 'long' %>
        </div>
        <!-- メールアドレス -->
        <div class="field">
          <%= f.label :メールアドレス, class: 'labelname' %><br />
          <%= f.email_field :email, autofocus: true, autocomplete: "email", class: 'long' %>
        </div>
        <!--パスワード-->
        <div class="field">
         <%= f.label :パスワード, class: 'labelname' %>
         <% if @minimum_password_length %>
          <em>(<%= @minimum_password_length %> characters minimum)</em>
           <% end %><br />
            <%= f.password_field :password, autocomplete: "new-password", class: 'long' %>
           </div>
          <div class="field">
           <%= f.label :パスワード（確認）, class: 'labelname' %><br />
           <%= f.password_field :password_confirmation, autocomplete: "new-password", class: 'long' %>
          </div>
         <div class="field">
          <%= f.label :現在のパスワードを入力ください, class: 'labelname' %> <i>(we need your current password to confirm your changes)</i><br />
          <%= f.password_field :current_password, autocomplete: "current-password", class: 'long' %>
         </div>
        <% if flash[:alert] %>
         <div class="alert alert-danger">
          <%= flash[:alert] %>
         </div>
        <% end %>
       <div class="actions btncenter">
        <%= f.submit "ユーザー情報更新", class: 'labelname btn-square-pop' %>
       </div>
     <% end %>
    </div>
     <div class="col-md-2"></div>
    </div>
   </div>

app/views/endusers/show.html.erb
<div class="container">
  <div class="row">
  	<h1><%= @enduser.name %>のマイページ</h1>
    <div style="padding: 5px; margin-top: 20px; margin-bottom: 10px; border: 1px solid #00008B; border-radius: 10px;">
      <table class="table table-striped">
        <tbody>
        	<%= attachment_image_tag @enduser, :profile_image, :fill, 128, 128, class: "img-circle profile-thumb", fallback: "/images/no_image100.jpg"%>
          <tr style="background-color:#f5f5f5">
	          <th><p>お名前</p></th>
	          <th><p>メールアドレス</p></th>
	      </tr>
	      <tr style="background-color:#f5f5f5">
	          <th><%= @enduser.name %></th>
      	      <th><%= @enduser.email %></th>
          </tr>
        </tbody>
      </table>
      <%= link_to edit_enduser_path(@enduser), class: 'btn-default' do %>
          <%= 'ユーザー情報編集' %>
          <button type="button" class="btn btn-default btn-block" ><span class="glyphicon glyphicon-wrench" aria-hidden="true"></span></button>
        <% end %>
    </div>
  </div>

    <div class="row">
      <div class="trip">
        <table class="table table-respansive">
          <table class="table table-hover">
            <% @trips.each do |trip| %>
              <tr>
                <td><%= link_to trip.title, trip_path(trip.id) %></td>
                <td><%= trip.subtitle %></td>
                <td><span class="glyphicon glyphicon-heart" aria-hidden="true"> <%= trip.likes.count %></td>
                <td><%= attachment_image_tag trip.enduser, :profile_image, :fill, 50, 50, class: "img-circle profile-thumb", fallback: "/images/no_image.jpg"%></td>
                <td><%= trip.enduser.name %></td>
              </tr>
          <% end %>
          </table>
        </table>
      </div>
    </div>
      <div class="paginate" style="font-size: 20px">
        <%= paginate(@trips) %>
      </div>
</div>