config/routes.rb
Rails.application.routes.draw do
  get 'admin_rankings/index'
  get 'rankings/index'
  root to: 'home#index'
  get 'home/index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  devise_for :endusers, controllers: {
    registrations: 'endusers/registrations',
    sessions: "endusers/sessions",
    passwords: "endusers/passwords"
  }

  devise_for :admins, controllers: {
    sessions:      'admins/sessions',
    passwords:     'admins/passwords',
    registrations: 'admins/registrations'
  }

  resources :endusers, only: [:edit, :show, :update, :destroy]
  resources :admins, only: [:index, :show, :destroy]

  resources :trips do
      resource :likes, only: [:create, :destroy]
  end

  resources :admin_trips, only: [:index, :show, :destroy]

  resources :rankings, only: [:index]
  resources :admin_rankings, only: [:index]

end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/day.rb
class Day < ApplicationRecord
	belongs_to :trip
	has_many :stays, dependent: :destroy, inverse_of: :day
    accepts_nested_attributes_for :stays, allow_destroy: true
end

app/models/enduser.rb
class Enduser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :trips, dependent: :destroy
  has_many :likes, dependent: :destroy
  acts_as_paranoid

  validates :name, presence: true
  validates :name, length: { in: 2..20 }
  attachment :profile_image

end

app/models/image.rb
class Image < ApplicationRecord
	belongs_to :stay
	attachment :image
end

app/models/like.rb
class Like < ApplicationRecord
	belongs_to :trip
	belongs_to :enduser
end

app/models/stay.rb
class Stay < ApplicationRecord
	belongs_to :day
	has_many :images, dependent: :destroy, inverse_of: :stay
	accepts_nested_attributes_for :images, allow_destroy: true
	accepts_attachments_for :images
  validates :comment,    length: { maximum: 250 }      # 「250文字以下」

    before_save :update_lonlat

    def update_lonlat
        lonlat = place_to_lonlat(read_attribute(:place))
        write_attribute(:lonlat, lonlat)
    end

    # 住所を保存用経緯度に変換
    def place_to_lonlat(place)
      result = Geocoder.search(place)
      if result.first
        lonlat = result.first.coordinates
        return lonlat.join(',')
      else
        return false
      end
    end

end

app/models/trip.rb
class Trip < ApplicationRecord
	belongs_to :enduser
	has_many :days, dependent: :destroy, inverse_of: :trip
	accepts_nested_attributes_for :days, allow_destroy: true
    validates :title,    length: { in: 1..50 }        # 「1文字以上50文字以下」
    validates :subtitle,    length: { maximum: 250 }      # 「250文字以下」
	has_many :likes, dependent: :destroy
	def enduser
      return Enduser.find_by(id: self.enduser_id)
    end

	def liked_by?(enduser)
		likes.where(enduser_id: enduser.id).exists?
    end
end

app/controllers/admin_trips_controller.rb
class AdminTripsController < ApplicationController

  def index
    @q = Trip.ransack(params[:q])
    @trips = @q.result(distinct: true).page(params[:page]).per(10).reverse_order
  end

  def search
    @q = Trip.search
    @trips = @q.result(distinct: true)
  end

  def show
      @trip = Trip.find(params[:id])
      @trips = Trip.all.includes(:days, :stays, :images)
  end

  def destroy
      @trip = Trip.find(params[:id])
      @trip.destroy
      redirect_to admin_trips_path
  end


  private
    def trip_params
    params.require(:trip).permit(:title, :subtitle,
    	  days_attributes: [:id, :day, :_destroy,
        stays_attributes: [:id, :time, :country, :place, :money, :comment, :status, :_destroy,
        images_attributes: [:id, :image, :_destroy]]])
    end

end

app/controllers/admins_controller.rb
class AdminsController < ApplicationController

  def index
    @q = Enduser.ransack(params[:q])
    @endusers = @q.result(distinct: true).page(params[:page]).per(10).reverse_order
  end

  def search
    @q = Enduser.search
    @endusers = @q.result(distinct: true)
  end

  def show
      @enduser = Enduser.find(params[:id])
      @trips = @enduser.trips.page(params[:page]).per(10).reverse_order
  end

  def destroy
      Enduser.find(params[:id]).destroy
    if admin_signed_in?
      redirect_to trips_path
    else
      redirect_to admins_trips_path
    end
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
    def create
        @trip = Trip.find(params[:trip_id])
        @like = current_enduser.likes.new(trip_id: @trip.id)
        @like.save
        render :create
    end
    def destroy
        @trip = Trip.find(params[:trip_id])
        @like = current_enduser.likes.find_by(trip_id: @trip.id)
        @like.destroy
        render :destroy
    end
end

app/controllers/trips_controller.rb
class TripsController < ApplicationController
before_action :ensure_correct_enduser, {only: [:edit, :update, :destroy]}
before_action :search

  def ensure_correct_enduser
  @trip = Trip.find_by(id: params[:id])
    if current_enduser.id != @trip.enduser_id
       flash[:notice] = "権限がありません"
       redirect_to trips_path
    end
  end

  def index
  	@q = Trip.ransack(params[:q])
    @trips = @q.result(distinct: true).page(params[:page]).per(10).reverse_order
    @random = Image.all.shuffle
  end

  def search
    @q = Trip.search
    @trips = @q.result(distinct: true)
  end

  def show
    @trip = Trip.find_by(id: params[:id])
    @trips = Trip.all
    @enduser = @trip.enduser
  end

  def new
  	@trip = Trip.new
  	@day = @trip.days.build
  	@stay = @day.stays.build
  	@image = @stay.images.build
  end

  def create
      @trip = Trip.new(trip_params)
      @trip.enduser_id = current_enduser.id
      @enduser = current_enduser
      @trips = Trip.all.order(created_at: :desc)
      if @trip.save
         redirect_to trips_path
         flash[:notice] = "You have creatad book successfully."
      else
         render 'trips/new'
      end
  end

  def edit
      @trip = Trip.find(params[:id])
      if @trip.enduser == current_enduser
      else
        redirect_to trips_path
      end
  end

  def update
      @trip = Trip.find(params[:id])
      @trip.update(trip_params)
      if @trip.save
        redirect_to trip_path(@trip)
        flash[:notice] = "You have edited book successfully"
      else
        render :edit
      end
  end

  def destroy
      @trip = Trip.find(params[:id])
      @trip.destroy
      redirect_to trips_path
  end

  private
    def trip_params
    params.require(:trip).permit(:title, :subtitle,
    	  days_attributes: [:id, :day, :_destroy,
        stays_attributes: [:id, :time, :country, :place, :money, :comment, :status, :lonlat, :_destroy,
        images_attributes: [:id, :image, :_destroy]]])
    end
end

app/helpers/admin_rankings_helper.rb
module AdminRankingsHelper
end

app/helpers/admin_trips_helper.rb
module AdminTripsHelper
end

app/helpers/admins_helper.rb
module AdminsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/endusers_helper.rb
module EndusersHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/rankings_helper.rb
module RankingsHelper
end

app/helpers/trips_helper.rb
module TripsHelper
end

app/views/admin_trips/_mapreader.html.erb
    <!-- APIでマップ実装 -->
    <% i = 0 %>
      <% @trip.days.each do |day| %>
        <% day.stays.each do |stay| %>
        <% i += 1 %>
        <div id="<%= i %>" data-json="<%= stay.lonlat.to_json %>" ></div>
        <% end %>
      <% end %>
        <div id="j_end" data-json="<%= i.to_json %>" ></div>
    <script type="text/javascript">
            var osmUrl='http://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png';
            var osmAttrib='&copy; <a href="http://osm.org/copyright">OpenStreetMap</a> contributors'
            var osm = new L.TileLayer(osmUrl, {attribution: osmAttrib});
            var map = new L.Map('map').addLayer(osm).setView([48.84845, 10.29694], 1);
            var j_end = JSON.parse(document.getElementById("j_end").dataset.json);
            for (var j=1; j<=j_end; j++){
                var lonlat = JSON.parse(document.getElementById(j).dataset.json);
                if (lonlat != null){
                    L.marker( lonlat.split(',')).addTo(map);
                }
            }
    </script>

app/views/admin_trips/index.html.erb
<div class="container">
  <!-- 検索フォーム -->
  <div class="searchbtn">
    <%= search_form_for(@q, url:admin_trips_path) do |f| %>
      <span class="glyphicon glyphicon-search" aria-hidden="true"></span>
      <%= f.search_field :title_or_subtitle_cont %>
      <%= f.submit '検索', class: 'btn btn-primary'  %>
    <% end %>
  </div>

  <body>
    <div class="row">
      <div class="trip">
        <table class="table table-responsive">
          <table class="table table-hover">
            <% @trips.each do |trip| %>
                  <tr>
                    <td><%= link_to trip.title, admin_trip_path(trip.id) %></td>
                    <td><%= trip.subtitle %></td>
                    <td><span class="glyphicon glyphicon-heart" aria-hidden="true"> <%= trip.likes.count %></td>
                    <td><%= attachment_image_tag trip.enduser, :profile_image, :fill, 50, 50, class: "img-circle profile-thumb", fallback: "/images/no_image.jpg"%></td>
                    <td><%= trip.enduser.name %></td>
                  </tr>
          <% end %>
          </table>
        </table>
      </div>
    </div>
    <div class="paginate" style="font-size: 20px">
      <%= paginate(@trips) %>
    </div>

  </body>
</div>

app/views/admin_trips/show.html.erb
<div class="container">
  <div class="new">
    <div class="row">
      <div class="col-md-5">
          <div class="margin-bottom">
            <b style="font-size:14px;"><%= @trip.title %></br></b>
            <b style="font-size:10px;"><%= @trip.subtitle %><br></b>
          </div>
          <div class="like">
            <span class="glyphicon glyphicon-heart" aria-hidden="true"> <%= @trip.likes.count %></span>
          </div>
          <div class="tripdata">
            <% @trip.days.each do |day| %>
              <% day.stays.each do |stay| %>
                  <b style="font-size:20px;"><%= day.day %>日目</br></b>
                  <%= stay.time.strftime("%R") %>
                  <%= stay.status %>
                  <%= stay.country %>
                  <%= stay.place %>
                  <%= stay.money %>¥
                  <%= stay.comment %></br>
                  <table class="table">
                    <% stay.images.each do |image| %>
                      <tr>
                        <td><%= attachment_image_tag image, :image, :fill, 100, 100 %></td>
                      </tr>
                    <% end %>
                  </table>
              <% end %>
            <% end %>
          </div>

          <div class="tripshowbtn">
            <% if admin_signed_in? %>
              <td><%= link_to "削除", admin_trip_path, model: @trip, method: :delete, data: { confirm: 'Are you sure?' }, class: "pull-danger", class: "btn btn-danger btn-xs" %></td>
            <% end %>
          <%= link_to "一覧画面に行く", admin_trips_path, class: 'btn btn-default' %>
          </div>
      </div>
    </div>
  </div>

  <div class="col-md-7">
    <div class="row">
      <div id="map">
        <div class="mapcss">
          <%= render :partial => "mapreader" %>
        </div>
      </div>
    </div>
  </div>
</div>